name: Rust CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: dtolnay/rust-toolchain@stable
              with:
                  targets: "thumbv6m-none-eabi"
                  components: "clippy,rustfmt"
            - uses: Swatinem/rust-cache@v2 # Optional: for faster builds
            - name: Build package
              run: cargo build --verbose
            - name: Build RP Pico example
              run: cargo build --verbose
              working-directory: ./examples/pico-example
            - name: Run tests
              run: cargo test --verbose
            - name: Check formatting
              run: cargo fmt -- --check
            - name: Run Clippy
              run: cargo clippy -- -W clippy::pedantic -D warnings # Treat warnings as errors
            - name: Check if README is up to date
              run: |
                  cargo install cargo-rdme
                  cargo rdme --check
